Dcreator/src/objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dcreator/src/objects/Employee__c.object
<CustomObject>
    <customHelpPage>EmployeeHelp</customHelpPage>
    <fields>
        <fullName>DateOfBirth__c</fullName>
        <label>DateOfBirth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>Employees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>VisaStatus__c</fullName>
        <label>VisaStatus</label>
        <picklist>
            <picklistValues>
                <fullName>F1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H1B</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dcreator/src/classes/myEmpRecord.cls
public class myEmpRecord {

    public Employee__c emp1 = new employee__c();

    public String ename { get; set; }


public void myEmpRecord()
{}


    public PageReference Submit() {
    
    try{

        insert emp1;
}catch(Exception e)

{

//print the error message on visual force
 ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL,''+ename);
 apexpages.addmessage(myMsg); 
}

    
    return null;
    }
 









public Employee__c getEmployee(){        
        return emp1;
    }





/*
//department__c d = new department__c();
//d.name = 'adminDept';
//insert d;


//employee__c e = new employee__c();
//e.name= 'testBob';
//e.department__c=d.id;
//e.DateOfBirth__c= date.today()+8000;

//e.Salary__c=1000;
//e.Gender__c='male';
 //e.VisaStatus__c='f1'; 
//insert e;*/
}